# Tutorial bookkeeping

In this notebook, we explain how to use the LaCE bookkeeping

## Read data

In [1]:
from lace.archive import pnd_archive

#### Read Cabayol23 post-processing

In [4]:
archive = pnd_archive.archivePND()
len(archive.data)

9900

In [5]:
# nsim pairs * nphases * naxes * nscalings * nsnaps
30 * 2 * 3 * 5 * 11

9900

#### Read Cabayol23 post-processing while dropping a simulation

In [6]:
archive = pnd_archive.archivePND(drop_sim=10)
len(archive.data)

9570

In [7]:
# nsim * nphases * naxes * nscalings * nsnaps
29 * 2 * 3 * 5 * 11

9570

#### Read growth simulation from new post-processing 
Also works for other especial simulations (see below)

In [8]:
_ = pnd_archive.get_sim_option_list(sim_suite="Cabayol23")
sim_option_list, sim_especial_list, sim_option_dict = _
sim_especial_list

['growth', 'neutrinos', 'central', 'seed', 'curved', 'reionization', 'running']

In [9]:
for sim in sim_especial_list:
    archive = pnd_archive.archivePND(pick_sim=sim)
    print(sim, len(archive.data))

growth 330
Sim has neutrinos
neutrinos 330
central 330
seed 330
curved 330
reionization 330
running 330


In [10]:
# nsim * nphases * naxes * nscalings * nsnaps
1 * 2 * 3 * 5 * 11

330

#### Read Pedersen+21 post-processing

In [11]:
archive = pnd_archive.archivePND(sim_suite="Pedersen21")
len(archive.data)

1980

In [12]:
# nsim * nphases * naxes * nscalings * nsnaps
30 * 2 * 1 * 3 * 11

1980

#### Read growth simulation from Pedersen+21 post-processing 
Also works for nu, central, or a number

In [13]:
archive = pnd_archive.archivePND(sim_suite="Pedersen21", pick_sim="growth")
len(archive.data)

22

In [14]:
# nsim * nphases * naxes * nscalings * nsnaps
1 * 2 * 1 * 1 * 11

22

## Compute averages

#### Read Cabayol+23 post-processing, then compute different types of averages
It also works for Pedersen+21

In [15]:
from lace.archive import pnd_archive

In [16]:
archive = pnd_archive.archivePND(sim_suite="Cabayol23")
len(archive.data)

9900

In [17]:
# nsim * nphases * naxes * nscalings * nsnaps
30 * 2 * 3 * 5 * 11

9900

In [18]:
archive.average_over_samples(flag="all")
archive.average_over_samples(flag="phases")
archive.average_over_samples(flag="axes")
print(
    len(archive.data_av_phases),
    len(archive.data_av_axes),
    len(archive.data_av_all),
)

4950 3300 1650


In [19]:
# nsim * nphases * naxes * nscalings * nsnaps
print(30 * 1 * 3 * 5 * 11)
print(30 * 2 * 1 * 5 * 11)
print(30 * 1 * 1 * 5 * 11)

4950
3300
1650


## Inputs for emulator

In [29]:
from lace.archive import pnd_archive, interface_archive

#### Cabayol+23 (using pnd_archive)

In [28]:
# read post-processing
archive = pnd_archive.archivePND(sim_suite="Cabayol23")
archive.get_training_data()
print(len(archive.training_data))

# nsim * nphases * naxes * nscalings * nsnaps
n_av_phases = 30 * 1 * 3 * 5 * 11
n_av_axes   = 30 * 2 * 1 * 5 * 11
n_av_all    = 30 * 1 * 1 * 5 * 11
print(n_av_phases + n_av_axes + n_av_all)

9900
9900


#### Cabayol+23 (using interface_archive)

In [30]:
archive = interface_archive.Archive()
archive.get_training_data(training_set='Cabayol23')
print(len(archive.training_data))

# nsim * nphases * naxes * nscalings * nsnaps
n_av_phases = 30 * 1 * 3 * 5 * 11
n_av_axes   = 30 * 2 * 1 * 5 * 11
n_av_all    = 30 * 1 * 1 * 5 * 11
print(n_av_phases + n_av_axes + n_av_all)

The list of simulation suites available is: ['Pedersen21', 'Cabayol23', '768_768', 'Nyx']
9900
9900


## Understanding the data

In [32]:
import numpy as np

In [31]:
archive = pnd_archive.archivePND(sim_suite='Cabayol23')
len(archive.data)

9900

In [33]:
# nsim * nphases * naxes * nscalings * nsnaps
30 * 2 * 3 * 5 * 11

9900

Simulation index

In [35]:
print(np.unique(archive.ind_sim))
archive.data[0]['ind_sim']

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


0

Phase index

In [37]:
print(np.unique(archive.ind_phase))
archive.data[0]['ind_phase']

[0. 1.]


0

Snapshot index

In [52]:
uni_z = np.unique(archive.ind_z)
print(uni_z)
for ii in range(0, len(uni_z)*30, 30):
    print(archive.data[ii]['ind_z'], archive.data[ii]['z'])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
0 4.5
1 4.25
2 4.0
3 3.75
4 3.5
5 3.25
6 3.0
7 2.75
8 2.5
9 2.25
10 2.0


Axis index

In [38]:
print(np.unique(archive.ind_axis))
archive.data[0]['ind_axis']

[0. 1. 2.]


0

Scaling index

In [53]:
uni_tau = np.unique(archive.ind_tau)
print(uni_tau)
for ii in range(len(uni_tau)):
    print(archive.data[ii]['ind_tau'], archive.data[ii]['scale_tau'])

[0. 1. 2. 3. 4.]
0 0.9
1 1.0
2 1.1
3 0.95
4 1.05
